CRUD/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

app1/urls.py
from django.contrib import admin
from django.urls import path
from .import views

urlpatterns = [
    path('add', views.add, name='add'),
    path('show', views.show, name='show'),
    path('', views.ShowDetailsPage, name='ShowDetailsPage'),
    path('EditPage/<id>', views.EditPage, name='EditPage'),
    path('SaveEdit', views.SaveEdit, name='SaveEdit'),
    path('ConfirmDelete/<id>', views.ConfirmDelete, name='ConfirmDelete'),
]

app1/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=70)
    email = models.EmailField(max_length=70)
    password = models.CharField(max_length=70)   

app1/forms.py
from dataclasses import field, fields
from django.forms import ModelForm
from .models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'
  

app1/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from .forms import UserForm
from .models import User
# Create your views here.
def add(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        form.save()
    return redirect("show")

def show(request):
    stud = User.objects.all()
    return render(request, "view.html", {'stu':stud})

def ShowDetailsPage(request):
    form = UserForm(request.POST or None)
    return render(request, "index.html", {'form': form})

def EditPage(request, id):
    data = User.objects.get(id = id)
    return render(request, "edit.html", {'data': data})

def SaveEdit(request):
    data = User.objects.get(id = request.POST['id'])
    form = UserForm(request.POST or None, instance=data)
    if form.is_valid():
        form.save()
    return redirect("show")


def ConfirmDelete(request, id):
    User.objects.filter(id=id).delete()
    return redirect("show")

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock title %} | CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">CrudProject</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Dropdown
                        </a>
                        
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Function Based View ModelForm CRUD Project</h2>
        {% block content %} {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

templates/edit.html
{% extends 'base.html' %}

{% block title %} {% endblock title %}

{% block content %}
{% load crispy_forms_tags%}
<h2><b>User_Form</b></h2>
<hr>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <form action="/SaveEdit" method="post">
               {% csrf_token %}
               <input type="hidden" name="id" value="{{data.id}}">
                <div id="div_id_name" class="control-group"> 
                    <label for="id_name" class="control-label requiredField">Name
                        <span class="asteriskField">*</span> 
                    </label> 
                    <div class="controls"> 
                        <input value="{{data.name}}" type="text" name="name" maxlength="70" class="textinput textInput" required="" id="id_name"> 
                    </div> 
                </div> 
                <div id="div_id_email" class="control-group"> 
                    <label for="id_email" class="control-label requiredField">Email
                        <span class="asteriskField">*</span> 
                    </label> 
                    <div class="controls"> 
                        <input value="{{data.email}}" type="email" name="email" maxlength="70" class="emailinput" required="" id="id_email"> 
                    </div> 
                </div>
                <div id="div_id_password" class="control-group"> 
                    <label for="id_password" class="control-label requiredField">
                 Password
                 <span class="asteriskField">*</span> 
                </label> 
                <div class="controls"> 
                    <input value="{{data.password}}" type="text" name="password" maxlength="70" class="textinput textInput" required="" id="id_password"> 
                </div> 
            </div>
                <input type="submit" value="Update">
                <a href="/show">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block title %} {% endblock title %}

{% block content %}
{% load crispy_forms_tags%}
<h2><b>User_Form</b></h2>
<hr>
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <form action="/add" method="post">
               {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Add">
                <a href="show">Show Record</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/view.html
{% extends 'base.html' %}

{% block title %} {% endblock title %}

{% block content %}
{% if stu %}
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Password</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for st in stu %}
        <tr>
            <th scope="row">{{st.id}}</th>
            <td>{{st.name}}</td>
            <td>{{st.email}}</td>
            <td>{{st.password}}</td>
            <td><a href="/EditPage/{{st.id}}">Edit</a></td>
            <td><a href="/ConfirmDelete/{{st.id}}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h4 class="text-center alert alert-warning"> No records</h4>
{% endif %}
<a href="/">Add New record</a>
{% endblock content %}